#pragma once
#include "Define.h"

#define NUMBER_OF_PLATFORMS_IN_FILE 2
#define NUMBER_OF_LADDERS_IN_FILE 1
#define NUMBER_OF_BARRELS_IN_FILE 1
#define NUMBER_OF_TROPHIES_IN_FILE 1

#define NUMBER_OF_PLATFORMS 10
#define PLATFORM_WIDTH 20

#define PLATFORM_I_HEIGHT 440
#define PLATFORM_II_HEIGHT 360
#define PLATFORM_III_HEIGHT 280
#define PLATFORM_IV_HEIGHT 200
#define PLATFORM_V_HEIGHT 120

#define PLATFORM1_I_X_CORD 60
#define PLATFORM1_II_X_CORD 520
#define PLATFORM1_III_X_CORD 440
#define PLATFORM1_IV_X_CORD 40
#define PLATFORM1_V_X_CORD 480
#define PLATFORM1_VI_X_CORD 340
#define PLATFORM1_VII_X_CORD 60
#define PLATFORM1_VIII_X_CORD 100
#define PLATFORM1_IX_X_CORD 470
#define PLATFORM1_X_X_CORD 280

#define PLATFORM1_I_LENGTH 80
#define PLATFORM1_II_LENGTH 160
#define PLATFORM1_III_LENGTH 200
#define PLATFORM1_IV_LENGTH 200
#define PLATFORM1_V_LENGTH 245
#define PLATFORM1_VI_LENGTH 350

#define PLATFORM2_I_X_CORD 60
#define PLATFORM2_II_X_CORD 650
#define PLATFORM2_III_X_CORD 440
#define PLATFORM2_IV_X_CORD 40
#define PLATFORM2_V_X_CORD 500
#define PLATFORM2_VI_X_CORD 100
#define PLATFORM2_VII_X_CORD 100
#define PLATFORM2_VIII_X_CORD 380
#define PLATFORM2_IX_X_CORD 470
#define PLATFORM2_X_X_CORD 260

#define PLATFORM2_I_LENGTH 60
#define PLATFORM2_II_LENGTH 160
#define PLATFORM2_III_LENGTH 200
#define PLATFORM2_IV_LENGTH 240
#define PLATFORM2_V_LENGTH 300
#define PLATFORM2_VI_LENGTH 550

#define PLATFORM3_I_X_CORD 60
#define PLATFORM3_II_X_CORD 420
#define PLATFORM3_III_X_CORD 660 
#define PLATFORM3_IV_X_CORD 40
#define PLATFORM3_V_X_CORD 440
#define PLATFORM3_VI_X_CORD 100
#define PLATFORM3_VII_X_CORD 500
#define PLATFORM3_VIII_X_CORD 60
#define PLATFORM3_IX_X_CORD 420
#define PLATFORM3_X_X_CORD 260

#define PLATFORM3_I_LENGTH 40
#define PLATFORM3_II_LENGTH 160
#define PLATFORM3_III_LENGTH 200
#define PLATFORM3_IV_LENGTH 220
#define PLATFORM3_V_LENGTH 250
#define PLATFORM3_VI_LENGTH 300
#define PLATFORM3_VII_LENGTH 350

#define NUMBER_OF_LADDERS 5
#define LADDER_WIDTH 18
#define LADDER_HEIGHT 80
#define LADDER_I_HEIGHT 160
#define LADDER_V_HEIGHT 60

#define LADDER_I_X_CORD 350
#define LADDER_II_X_CORD 600
#define LADDER_III_X_CORD 150
#define LADDER_IV_X_CORD 550
#define LADDER_V_X_CORD 110

#define NUMBER_OF_BARRELS 8
#define BARRELS_WIDTH 22
#define BARRELS_DIFFERENCE_IN_Y 5
#define BARRELS_HITBOX_SIZE 8
#define BARRELS_REAL_SIZE 20

#define BARRELS_I_SPAWN_POINT_X 280
#define BARRELS_SPAWN_POINT_Y 120

#define BARRELS_II_SPAWN_POINT_X BARRELS_I_SPAWN_POINT_X + 50
#define BARRELS_III_SPAWN_POINT_X BARRELS_I_SPAWN_POINT_X + 220
#define BARRELS_IV_SPAWN_POINT_X BARRELS_I_SPAWN_POINT_X + 300
#define BARRELS_V_SPAWN_POINT_X BARRELS_I_SPAWN_POINT_X + 380
#define BARRELS_VI_SPAWN_POINT_X  BARRELS_I_SPAWN_POINT_X - 120
#define BARRELS_VII_SPAWN_POINT_X  BARRELS_I_SPAWN_POINT_X - 160
#define BARRELS_VIII_SPAWN_POINT_X BARRELS_I_SPAWN_POINT_X - 200

#define BARRELS_BOWLING_SPEED 16
#define BARRELS_FALLING_SPEED GRAVITY_SPEED * 20

#define NUMBER_OF_TROPHIES 3
#define TROPHIES_DIFFERENCE_IN_Y 10
#define TROPHIES_REAL_SIZE 20

#define TROPHIES1_I_SPAWN_POINT_X 200
#define TROPHIES1_II_SPAWN_POINT_X 320
#define TROPHIES1_III_SPAWN_POINT_X 650

#define TROPHIES2_I_SPAWN_POINT_X 670
#define TROPHIES2_II_SPAWN_POINT_X 70
#define TROPHIES2_III_SPAWN_POINT_X 400

#define TROPHIES3_I_SPAWN_POINT_X 675
#define TROPHIES3_II_SPAWN_POINT_X 350
#define TROPHIES3_III_SPAWN_POINT_X 620

#define LIVES_SPAWN_POINT_X 70
#define LIVES_REAL_SIZE 16