#pragma once
//REMEMBER: GET RID OF MAGIC NUMBERS !!!

#define SCREEN_WIDTH	720
#define SCREEN_HEIGHT	520
#define SECONDS_BETWEEN_REFRESH 0.5
#define REFRESH_RATE 1/SECONDS_BETWEEN_REFRESH

#define X 0
#define Y 1
#define playerX 300
#define playerY 400
#define TEN_ROW 10
#define END_OF_SCREEN_HEIGHT SCREEN_HEIGHT - 12
#define GROUND_HEIGHT SCREEN_HEIGHT - 20